language: java
jdk:
  - oraclejdk8
before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
notifications:
  email: false
after_success:
  - mvn org.eluder.coveralls:coveralls-maven-plugin:report
